definitions:
  model.AuthResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  model.Comment:
    properties:
      author:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      movieId:
        type: string
      updatedAt:
        type: string
    type: object
  model.Credential:
    properties:
      id:
        type: string
      password:
        type: string
    type: object
  model.Empty:
    type: object
  model.Error:
    properties:
      message:
        type: string
    type: object
  model.Movie:
    properties:
      director:
        type: string
      genre:
        items:
          type: string
        type: array
      id:
        type: string
      posterUrl:
        type: string
      reviewCounts:
        type: integer
      reviewScore:
        type: number
      story:
        type: string
      title:
        type: string
    type: object
  model.RefreshToken:
    properties:
      refreshToken:
        type: string
    type: object
  model.RegisterForm:
    properties:
      email:
        type: string
      id:
        type: string
      nickname:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  model.UserInfo:
    properties:
      email:
        type: string
      id:
        type: string
      nickname:
        type: string
      phone:
        type: string
      uid:
        type: string
    type: object
  model.UserInfoForm:
    properties:
      email:
        type: string
      nickname:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for a movie API.
  title: Movie API
  version: 2.1.1
paths:
  /auth/authorize:
    post:
      consumes:
      - application/json
      description: Authorize with id and password
      parameters:
      - description: Credential
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Credential'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
      summary: Authorize with credential
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Authorize with refresh token
      parameters:
      - description: RefreshToken
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
      summary: Authorize with refresh token - not implemented
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register with id and password
      parameters:
      - description: Register
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "409":
          description: Duplicated id
          schema:
            $ref: '#/definitions/model.Error'
      summary: Register with credential
      tags:
      - auth
  /movies:
    get:
      description: Get all movies
      parameters:
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Empty'
            - properties:
                movies:
                  items:
                    $ref: '#/definitions/model.Movie'
                  type: array
              type: object
      summary: Get all movies
      tags:
      - movies
  /movies/{id}:
    get:
      description: Get movie detail (including story)
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Movie'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Error'
      summary: Get movie detail
      tags:
      - movies
  /movies/{id}/comments:
    get:
      description: Get comments of movies
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Empty'
            - properties:
                comments:
                  items:
                    $ref: '#/definitions/model.Comment'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Error'
      summary: Get movie comments - currently implementing...
      tags:
      - movies
  /users/me:
    get:
      description: Get information of logged in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserInfo'
      security:
      - JWT: []
      summary: Get my information
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update information of logged in user
      parameters:
      - description: User information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserInfoForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserInfo'
      security:
      - JWT: []
      summary: Update my information
      tags:
      - users
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
